enum BiwaBokubokuSpriteArt {
    static let palette: [Character: UInt32] = [
        "k": 0x24160f,
        "W": 0xe0b070,
        "m": 0xc98d4f,
        "d": 0x8a5a2e,
        "w": 0xfff3da,
        "S": 0x5e5870,
        "N": 0x4a4458,
        "n": 0x332f42,
        "b": 0x80512f,
        "B": 0x4a2e1f,
        "l": 0xe8c9a8,
    ]

    private static func make(_ name: String, rows: [String]) -> PixelSpriteDefinition {
        PixelSpriteDefinition(
            name: name,
            rows: rows,
            palette: palette,
            anchorX: 20,
            baselineY: 45
        )
    }

    private static let idleNeutral = make("biwa.idle", rows: [
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        ".............B..B.......................",
        "............kdmmdddk....................",
        "..........BBkdmmdddk....................",
        "............kdddkkmWWmk.................",
        "..........BBkkkkkkmWWmk.................",
        "................kBBBBBBk................",
        "...............kWwWwWwWwk...............",
        "..............kmWwWwWwWwmk..............",
        ".............kmmWwWwWwWwmmk.............",
        "............kmWWWwWwWwWwWWmk............",
        "...........kmkkkWwWwWwWwkkkmk...........",
        "...........kmmkmWwWwWwWwmkmmk...........",
        "...........kmWmWWwWwWwWwWWWmk...........",
        "...........kdmWWWwWwWwWwWWmdk...........",
        "...........kdmWWWwWwWwWwWmmdk...........",
        "...........kdmWWBBBBBBBBWWmdk...........",
        "............kdmWWWBBBBWWWmdk..k.........",
        ".............kddmmWWWWmmddk..kbk........",
        "...............kdddmmdddk....kbk........",
        ".............kSSSSnnnnSSSSk..kbk........",
        "...........kSSNNNNNnnNNNNNSSkkbk........",
        "..........kSNSNNNNNnnNNNNNNNNkbk........",
        ".........kSNNSNNNNNnnNNNNNNNNkbk........",
        ".........kSNNSNNNNNnnNNNNNNkkllk........",
        ".........kNNNSNNNNNnnNNNNNNkkllk........",
        ".........knNNSNNNNNnnNNNNNNk.kbk........",
        ".........knnnkNNNNNnnNNNNNnk.kbk........",
        "..........kkkkNNNNNnnNNNNNnk.kbk........",
        "............knNNNNNnnNNNNNnk.kbk........",
        "...........knNNNNNNnnNNNNNNnkkbk........",
        "...........knNNNNNNnnNNNNNNnkkbk........",
        "...........knnnnnnnnnnnnnnnnkkbk........",
        "...........kkkkkkkkkkkkkkkkkkkbk........",
        "..............kllk....kllk...kbk........",
        "..............kllk....kllk...kbk........",
        ".............kbbbbk..kbbbbk..kbk........",
        "..............BBBB....BBBB....B.........",
        "........................................",
        "........................................",
    ])

    private static let walkContact = make("biwa.walk.contact", rows: [
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        ".............B..B.......................",
        "............kdmmdddk....................",
        "..........BBkdmmdddk....................",
        "............kdddkkmWWmk.................",
        "..........BBkkkkkkmWWmk.................",
        "................kBBBBBBk................",
        "...............kWwWwWwWwk...............",
        "..............kmWwWwWwWwmk..............",
        ".............kmmWwWwWwWwmmk.............",
        "............kmWWWwWwWwWwWWmk............",
        "...........kmkkkWwWwWwWwkkkmk...........",
        "...........kmmkmWwWwWwWwmkmmk...........",
        "...........kmWmWWwWwWwWwWWWmk...........",
        "...........kdmWWWwWwWwWwWWmdk...........",
        "...........kdmWWWwWwWwWwWmmdk...........",
        "...........kdmWWBBBBBBBBWWmdk...........",
        "............kdmWWWBBBBWWWmdk...k........",
        ".............kddmmWWWWmmddk...kbk.......",
        "...............kdddmmdddk.....kbk.......",
        ".............kSSSSnnnnSSSSk...kbk.......",
        "...........kSSNNNNNnnNNNNNSSk.kbk.......",
        "..........kSNSNNNNNnnNNNNNNNNkkbk.......",
        ".........kSNNSNNNNNnnNNNNNNNNkkbk.......",
        ".........kSNNSNNNNNnnNNNNNNk.kllk.......",
        ".........kNNNSNNNNNnnNNNNNNk.kllk.......",
        ".........knNNSNNNNNnnNNNNNNk..kbk.......",
        ".........knnnkNNNNNnnNNNNNnk..kbk.......",
        "..........kkkkNNNNNnnNNNNNnk..kbk.......",
        "............knNNNNNnnNNNNNnk..kbk.......",
        "...........knNNNNNNnnNNNNNNnk.kbk.......",
        "...........knNNNNNNnnNNNNNNnk.kbk.......",
        "...........knnnnnnnnnnnnnnnnk.kbk.......",
        "...........kkkkkkkkkkkkkkkkkk.kbk.......",
        "............kllk........kllk..kbk.......",
        "............kllk........kllk..kbk.......",
        "...........kbbbbk......kbbbbk.kbk.......",
        "............BBBB........BBBB...B........",
        "........................................",
        "........................................",
    ])

    private static let walkRise = make("biwa.walk.rise", rows: [
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        ".............B..B.......................",
        "............kdmmdddk....................",
        "..........BBkdmmdddk....................",
        "............kdddkkmWWmk.................",
        "..........BBkkkkkkmWWmk.................",
        "................kBBBBBBk................",
        "...............kWwWwWwWwk...............",
        "..............kmWwWwWwWwmk..............",
        ".............kmmWwWwWwWwmmk.............",
        "............kmWWWwWwWwWwWWmk............",
        "...........kmkkkWwWwWwWwkkkmk...........",
        "...........kmmkmWwWwWwWwmkmmk...........",
        "...........kmWmWWwWwWwWwWWWmk...........",
        "...........kdmWWWwWwWwWwWWmdk...........",
        "...........kdmWWWwWwWwWwWmmdk...........",
        "...........kdmWWBBBBBBBBWWmdk...........",
        "............kdmWWWBBBBWWWmdk...k........",
        ".............kddmmWWWWmmddk...kbk.......",
        "...............kdddmmdddk.....kbk.......",
        ".............kSSSSnnnnSSSSk...kbk.......",
        "...........kSSNNNNNnnNNNNNSSk.kbk.......",
        "..........kSNSNNNNNnnNNNNNNNNkkbk.......",
        ".........kSNNSNNNNNnnNNNNNNNNkkbk.......",
        ".........kSNNSNNNNNnnNNNNNNk.kllk.......",
        ".........kNNNSNNNNNnnNNNNNNk.kllk.......",
        ".........knNNSNNNNNnnNNNNNNk..kbk.......",
        ".........knnnkNNNNNnnNNNNNnk..kbk.......",
        "..........kkkkNNNNNnnNNNNNnk..kbk.......",
        "............knNNNNNnnNNNNNnk..kbk.......",
        "...........knNNNNNNnnNNNNNNnk.kbk.......",
        "...........knNNNNNNnnNNNNNNnk.kbk.......",
        "...........knnnnnnnnnnnnnnnnk.kbk.......",
        "...........kkkkkkkkkkkkkkkkkk.kbk.......",
        ".............kllk......kllk...kbk.......",
        ".............kllk......kllk...kbk.......",
        ".............kllk.....kbbbbk..kbk.......",
        "............kbbbbk.....BBBB...kbk.......",
        ".............BBBB..............B........",
        "........................................",
        "........................................",
    ])

    private static let walkCross = make("biwa.walk.cross", rows: [
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        ".............B..B.......................",
        "............kdmmdddk....................",
        "..........BBkdmmdddk....................",
        "............kdddkkmWWmk.................",
        "..........BBkkkkkkmWWmk.................",
        "................kBBBBBBk................",
        "...............kWwWwWwWwk...............",
        "..............kmWwWwWwWwmk..............",
        ".............kmmWwWwWwWwmmk.............",
        "............kmWWWwWwWwWwWWmk............",
        "...........kmkkkWwWwWwWwkkkmk...........",
        "...........kmmkmWwWwWwWwmkmmk...........",
        "...........kmWmWWwWwWwWwWWWmk...........",
        "...........kdmWWWwWwWwWwWWmdk...........",
        "...........kdmWWWwWwWwWwWmmdk...........",
        "...........kdmWWBBBBBBBBWWmdk...........",
        "............kdmWWWBBBBWWWmdk.k..........",
        ".............kddmmWWWWmmddk.kbk.........",
        "...............kdddmmdddk...kbk.........",
        ".............kSSSSnnnnSSSSk.kbk.........",
        "...........kSSNNNNNnnNNNNNSSkbk.........",
        "..........kSNSNNNNNnnNNNNNNNkbk.........",
        ".........kSNNSNNNNNnnNNNNNNNkbk.........",
        ".........kSNNSNNNNNnnNNNNNNkllk.........",
        ".........kNNNSNNNNNnnNNNNNNkllk.........",
        ".........knNNSNNNNNnnNNNNNNkkbk.........",
        ".........knnnkNNNNNnnNNNNNnkkbk.........",
        "..........kkkkNNNNNnnNNNNNnkkbk.........",
        "............knNNNNNnnNNNNNnkkbk.........",
        "...........knNNNNNNnnNNNNNNnkbk.........",
        "...........knNNNNNNnnNNNNNNnkbk.........",
        "...........knnnnnnnnnnnnnnnnkbk.........",
        "...........kkkkkkkkkkkkkkkkkkbk.........",
        "................kllk.kllk...kbk.........",
        "................kllk.kllk...kbk.........",
        "................kllkkbbbbk..kbk.........",
        "...............kbbbbkBBBB....B..........",
        "................BBBB....................",
        "........................................",
        "........................................",
    ])

    private static let walkSettle = make("biwa.walk.settle", rows: [
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        ".............B..B.......................",
        "............kdmmdddk....................",
        "..........BBkdmmdddk....................",
        "............kdddkkmWWmk.................",
        "..........BBkkkkkkmWWmk.................",
        "................kBBBBBBk................",
        "...............kWwWwWwWwk...............",
        "..............kmWwWwWwWwmk..............",
        ".............kmmWwWwWwWwmmk.............",
        "............kmWWWwWwWwWwWWmk............",
        "...........kmkkkWwWwWwWwkkkmk...........",
        "...........kmmkmWwWwWwWwmkmmk...........",
        "...........kmWmWWwWwWwWwWWWmk...........",
        "...........kdmWWWwWwWwWwWWmdk...........",
        "...........kdmWWWwWwWwWwWmmdk...........",
        "...........kdmWWBBBBBBBBWWmdk...........",
        "............kdmWWWBBBBWWWmdk..k.........",
        ".............kddmmWWWWmmddk..kbk........",
        "...............kdddmmdddk....kbk........",
        ".............kSSSSnnnnSSSSk..kbk........",
        "...........kSSNNNNNnnNNNNNSSkkbk........",
        "..........kSNSNNNNNnnNNNNNNNNkbk........",
        ".........kSNNSNNNNNnnNNNNNNNNkbk........",
        ".........kSNNSNNNNNnnNNNNNNkkllk........",
        ".........kNNNSNNNNNnnNNNNNNkkllk........",
        ".........knNNSNNNNNnnNNNNNNk.kbk........",
        ".........knnnkNNNNNnnNNNNNnk.kbk........",
        "..........kkkkNNNNNnnNNNNNnk.kbk........",
        "............knNNNNNnnNNNNNnk.kbk........",
        "...........knNNNNNNnnNNNNNNnkkbk........",
        "...........knNNNNNNnnNNNNNNnkkbk........",
        "...........knnnnnnnnnnnnnnnnkkbk........",
        "...........kkkkkkkkkkkkkkkkkkkbk........",
        "...............kllk....kllk..kbk........",
        "...............kllk....kllk..kbk........",
        "..............kbbbbk..kbbbbk.kbk........",
        "...............BBBB....BBBB...B.........",
        "........................................",
        "........................................",
    ])

    static let idle: [PixelSpriteDefinition] = [idleNeutral]
    static let walk: [PixelSpriteDefinition] = [walkContact, walkRise, walkCross, walkSettle]
    static let strong: [PixelSpriteDefinition] = []

    static let allDefinitions: [PixelSpriteDefinition] = idle + walk
}
