enum KappaSpriteArt {
    static let palette: [Character: UInt32] = [
        "k": 0x24160f,
        "G": 0x2e6b3d,
        "g": 0x4e9e5f,
        "l": 0x7cc472,
        "Y": 0xe8c85a,
        "y": 0xd5a32c,
        "o": 0xe08a3c,
        "b": 0x8a6a3a,
        "B": 0x5c452a,
        "c": 0xcaa46a,
        "w": 0xfff3da,
    ]

    private static func make(_ name: String, rows: [String]) -> PixelSpriteDefinition {
        PixelSpriteDefinition(
            name: name,
            rows: rows,
            palette: palette,
            anchorX: 20,
            baselineY: 45
        )
    }

    private static let idleNeutral = make("kappa.idle", rows: [
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "................kYYYYYYk................",
        "..............kyYYYyyYYYyk..............",
        "............kGkyyyyyyyyyykGk............",
        "...........kGGGkkkkkkkkkkGGGk...........",
        ".........kGllGGllllGGllllGGlGGk.........",
        "..........kggkkkkgllllgkkkkggk..........",
        "..........kgkwwwwkllllkwwwwkgk..........",
        "..........kgkwkkwkggggkwkkwkgk..........",
        "..........kgkwkkwkggggkwkkwkgk..........",
        "..........kggkkkkggggggkkkkggk..........",
        "..........kGllgkYYYYYYYYkgllGk..........",
        "..........kGlgkooooooooookglGk..........",
        "..........kGggkokkkkkkkkokggGk..........",
        "..........kGgggkooooooookgggGk..........",
        "...........kGgggkkkkkkkkgggGk...........",
        "........kkkkkGggggggggggggGkkkkk........",
        "........kgGkkbBggggggggggBbkkGgk........",
        "........kgGkkbBggBBBBBBggBbkkGgk........",
        "........kgGkkbBgBccccccBgBbkkGgk........",
        "........kgGkkbBgBccccccBgBbkkGgk........",
        "........kgGkkbBgBcBBBBcBgBbkkGgk........",
        ".......klllkkbBgBccccccBgBbkklllk.......",
        ".......klklkkbBgBccccccBgBbkklklk.......",
        "........kkk.kbBggBBBBBBggBbk.kkk........",
        "............kbBGggggggggGBbk............",
        "............kkkkBBBBBBBBkkkk............",
        ".............kggGk....kGggk.............",
        ".............kggGk....kGggk.............",
        ".............kggGk....kGggk.............",
        "...........klllllk....klllllk...........",
        "...........kGGkGGk....kGGkGGk...........",
        "........................................",
        "........................................",
    ])

    private static let walkContact = make("kappa.walk.contact", rows: [
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "................kYYYYYYk................",
        "..............kyYYYyyYYYyk..............",
        "............kGkyyyyyyyyyykGk............",
        "...........kGGGkkkkkkkkkkGGGk...........",
        ".........kGllGGllllGGllllGGlGGk.........",
        "..........kggkkkkgllllgkkkkggk..........",
        "..........kgkwwwwkllllkwwwwkgk..........",
        "..........kgkwkkwkggggkwkkwkgk..........",
        "..........kgkwkkwkggggkwkkwkgk..........",
        "..........kggkkkkggggggkkkkggk..........",
        "..........kGllgkYYYYYYYYkgllGk..........",
        "..........kGlgkooooooooookglGk..........",
        "..........kGggkokkkkkkkkokggGk..........",
        "..........kGgggkooooooookgggGk..........",
        "...........kGgggkkkkkkkkgggGk...........",
        "........kkkkkGggggggggggggGkkkkk........",
        "........kgGkkbBggggggggggBbkkGgk........",
        "........kgGkkbBggBBBBBBggBbkkGgk........",
        "........kgGkkbBgBccccccBgBbkkGgk........",
        "........kgGkkbBgBccccccBgBbkkGgk........",
        ".......klllkkbBgBcBBBBcBgBbkkGgk........",
        ".......klklkkbBgBccccccBgBbkkGgk........",
        "........kkk.kbBgBccccccBgBbkklllk.......",
        "............kbBggBBBBBBggBbkklklk.......",
        "............kbBGggggggggGBbk.kkk........",
        "............kkkkBBBBBBBBkkkk............",
        "............kggGk.....kGggk.............",
        "...........kggGk......kGggk.............",
        "...........kggGk......kGggk.............",
        ".........klllllk.....klllllk............",
        ".........kGGkGGk.....kGGkGGk............",
        "........................................",
        "........................................",
    ])

    private static let walkRise = make("kappa.walk.rise", rows: [
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "................kYYYYYYk................",
        "..............kyYYYyyYYYyk..............",
        "............kGkyyyyyyyyyykGk............",
        "...........kGGGkkkkkkkkkkGGGk...........",
        ".........kGllGGllllGGllllGGlGGk.........",
        "..........kggkkkkgllllgkkkkggk..........",
        "..........kgkwwwwkllllkwwwwkgk..........",
        "..........kgkwkkwkggggkwkkwkgk..........",
        "..........kgkwkkwkggggkwkkwkgk..........",
        "..........kggkkkkggggggkkkkggk..........",
        "..........kGllgkYYYYYYYYkgllGk..........",
        "..........kGlgkooooooooookglGk..........",
        "..........kGggkokkkkkkkkokggGk..........",
        "..........kGgggkooooooookgggGk..........",
        "...........kGgggkkkkkkkkgggGk...........",
        "........kkkkkGggggggggggggGkkkkk........",
        "........kgGkkbBggggggggggBbkkGgk........",
        "........kgGkkbBggBBBBBBggBbkkGgk........",
        "........kgGkkbBgBccccccBgBbkkGgk........",
        "........kgGkkbBgBccccccBgBbkkGgk........",
        "........kgGkkbBgBcBBBBcBgBbkkGgk........",
        ".......klllkkbBgBccccccBgBbkklllk.......",
        ".......klklkkbBgBccccccBgBbkklklk.......",
        "........kkk.kbBggBBBBBBggBbk.kkk........",
        "............kbBGggggggggGBbk............",
        "............kkkkBBBBBBBBkkkk............",
        ".............kggGk....kGggk.............",
        ".............kggGk....kGggk.............",
        ".............kggGk....kGggk.............",
        ".............kggGk...klllllk............",
        "...........klllllk...kGGkGGk............",
        "...........kGGkGGk......................",
        "........................................",
        "........................................",
    ])

    private static let walkCross = make("kappa.walk.cross", rows: [
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "................kYYYYYYk................",
        "..............kyYYYyyYYYyk..............",
        "............kGkyyyyyyyyyykGk............",
        "...........kGGGkkkkkkkkkkGGGk...........",
        ".........kGllGGllllGGllllGGlGGk.........",
        "..........kggkkkkgllllgkkkkggk..........",
        "..........kgkwwwwkllllkwwwwkgk..........",
        "..........kgkwkkwkggggkwkkwkgk..........",
        "..........kgkwkkwkggggkwkkwkgk..........",
        "..........kggkkkkggggggkkkkggk..........",
        "..........kGllgkYYYYYYYYkgllGk..........",
        "..........kGlgkooooooooookglGk..........",
        "..........kGggkokkkkkkkkokggGk..........",
        "..........kGgggkooooooookgggGk..........",
        "...........kGgggkkkkkkkkgggGk...........",
        "........kkkkkGggggggggggggGkkkkk........",
        "........kgGkkbBggggggggggBbkkGgk........",
        "........kgGkkbBggBBBBBBggBbkkGgk........",
        "........kgGkkbBgBccccccBgBbkkGgk........",
        "........kgGkkbBgBccccccBgBbkkGgk........",
        "........kgGkkbBgBcBBBBcBgBbkkGgk........",
        ".......klllkkbBgBccccccBgBbkklllk.......",
        ".......klklkkbBgBccccccBgBbkklklk.......",
        "........kkk.kbBggBBBBBBggBbk.kkk........",
        "............kbBGggggggggGBbk............",
        "............kkkkBBBBBBBBkkkk............",
        "..............kggGk..kGggk..............",
        "..............kggGk..kGggk..............",
        "..............kggGk..kGggk..............",
        "..............kggGk..kGggk..............",
        "............klllllk.klllllk.............",
        "............kGGkGGk.kGGkGGk.............",
        "........................................",
        "........................................",
    ])

    private static let walkSettle = make("kappa.walk.settle", rows: [
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "................kYYYYYYk................",
        "..............kyYYYyyYYYyk..............",
        "............kGkyyyyyyyyyykGk............",
        "...........kGGGkkkkkkkkkkGGGk...........",
        ".........kGllGGllllGGllllGGlGGk.........",
        "..........kggkkkkgllllgkkkkggk..........",
        "..........kgkwwwwkllllkwwwwkgk..........",
        "..........kgkwkkwkggggkwkkwkgk..........",
        "..........kgkwkkwkggggkwkkwkgk..........",
        "..........kggkkkkggggggkkkkggk..........",
        "..........kGllgkYYYYYYYYkgllGk..........",
        "..........kGlgkooooooooookglGk..........",
        "..........kGggkokkkkkkkkokggGk..........",
        "..........kGgggkooooooookgggGk..........",
        "...........kGgggkkkkkkkkgggGk...........",
        "........kkkkkGggggggggggggGkkkkk........",
        "........kgGkkbBggggggggggBbkkGgk........",
        "........kgGkkbBggBBBBBBggBbkkGgk........",
        "........kgGkkbBgBccccccBgBbkkGgk........",
        "........kgGkkbBgBccccccBgBbkkGgk........",
        "........kgGkkbBgBcBBBBcBgBbkklllk.......",
        "........kgGkkbBgBccccccBgBbkklklk.......",
        ".......klllkkbBgBccccccBgBbk.kkk........",
        ".......klklkkbBggBBBBBBggBbk............",
        "........kkk.kbBGggggggggGBbk............",
        "............kkkkBBBBBBBBkkkk............",
        ".............kggGk.....kGggk............",
        ".............kggGk......kGggk...........",
        ".............kggGk......kGggk...........",
        "............klllllk.....klllllk.........",
        "............kGGkGGk.....kGGkGGk.........",
        "........................................",
        "........................................",
    ])

    static let idle: [PixelSpriteDefinition] = [idleNeutral]
    static let walk: [PixelSpriteDefinition] = [walkContact, walkRise, walkCross, walkSettle]
    static let strong: [PixelSpriteDefinition] = []

    static let allDefinitions: [PixelSpriteDefinition] = idle + walk
}
