enum OniSpriteArt {
    static let palette: [Character: UInt32] = [
        "k": 0x24160f,
        "R": 0x8e2f2d,
        "r": 0xc94545,
        "c": 0xe45c5e,
        "w": 0xfff3da,
        "W": 0xe8d3ae,
        "s": 0xf5e6c8,
        "h": 0x2e2233,
        "b": 0x80512f,
        "B": 0x4a2e1f,
        "g": 0xd5a32c,
    ]

    private static func make(_ name: String, rows: [String]) -> PixelSpriteDefinition {
        PixelSpriteDefinition(
            name: name,
            rows: rows,
            palette: palette,
            anchorX: 20,
            baselineY: 45
        )
    }

    private static let idleNeutral = make("oni.idle", rows: [
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        ".............kwk........kwk.............",
        "............kwWk........kWwk............",
        "............kwWk.kk.....kWwk............",
        "...........khhhhkhhkkkkkhhhhk...........",
        "..........khhhhhhhhhhhhhhhhhhk..........",
        "..........khhhhhhhhhhhhhhhhhhhk.........",
        "..........khhhhhhhhhhhhhhhhhhk..........",
        "..........khhhcchhccchcchhchhk..........",
        "...........krcccckcccckccccrk...........",
        "...........krkkkkkcccckkkkkrk...........",
        "...........krkwwwkcccckwwwkrk...........",
        "...........krkwkwkcccckwkwkrk...........",
        ".......kkk.krccccccRRccccccrk...........",
        ".......ksk.krcckwkkkkkkwkccrk.kkk.......",
        ".......ksk.krcckwkkkkkkwkccrk.ksk.......",
        ".......ksk.krcckkkkkkkkkkccrk.ksk.......",
        ".......ksk.kRrrrrrrrrrrrrrrRk.ksk.......",
        ".......ksk..kkkkkkkkkkkkkkkk..ksk.......",
        ".......ksk.kcccccccccccccccck.ksk.......",
        ".......kskkrccBccccccccccBccrkksk.......",
        ".......krrkrcccBccccccccBcccrkrrk.......",
        ".......krrkrccccckkkkkkcccccrkrrk.......",
        "........kkkrccckkbbbbbbkkcccrkkk........",
        "..........krcckbgwwwwwwgbkccrk..........",
        "..........krrkbwwwwwwwwwwbkrrk..........",
        "..........krrkgwwwwwwwwwwgkrrk..........",
        "..........krrkBwwwwwwwwwwBkrrk..........",
        "..........krrkBWWWWWWWWWWBkrrk..........",
        "..........kRRkBWWWWWWWWWWBkRRk..........",
        "..........kRRrkBgWWWWWWgBkrRRk..........",
        "..........kkkkkkBBBBBBBBkkkkkk..........",
        "............krrkkkkkkkkkkrrk............",
        "............krrk........krrk............",
        "............krrk........krrk............",
        "...........kBBBk........kBBBk...........",
        "...........kBBBk........kBBBk...........",
        "........................................",
        "........................................",
    ])

    private static let walkContact = make("oni.walk.contact", rows: [
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        ".............kwk........kwk.............",
        "............kwWk........kWwk............",
        "............kwWk.kk.....kWwk............",
        "...........khhhhkhhkkkkkhhhhk...........",
        "..........khhhhhhhhhhhhhhhhhhk..........",
        "..........khhhhhhhhhhhhhhhhhhhk.........",
        "..........khhhhhhhhhhhhhhhhhhk..........",
        "..........khhhcchhccchcchhchhk..........",
        "...........krcccckcccckccccrk...........",
        "...........krkkkkkcccckkkkkrk...........",
        "...........krkwwwkcccckwwwkrk...........",
        "...........krkwkwkcccckwkwkrk...........",
        "...........krccccccRRccccccrk.kkk.......",
        ".......kkk.krcckwkkkkkkwkccrk.ksk.......",
        ".......ksk.krcckwkkkkkkwkccrk.ksk.......",
        ".......ksk.krcckkkkkkkkkkccrk.ksk.......",
        ".......ksk.kRrrrrrrrrrrrrrrRk.ksk.......",
        ".......ksk..kkkkkkkkkkkkkkkk..ksk.......",
        ".......ksk.kcccccccccccccccck.ksk.......",
        ".......kskkrccBccccccccccBccrkrrk.......",
        ".......kskkrcccBccccccccBcccrkrrk.......",
        ".......krrkrccccckkkkkkcccccrkkk........",
        ".......krrkrccckkbbbbbbkkcccrk..........",
        "........kkkrcckbgwwwwwwgbkccrk..........",
        "..........krrkbwwwwwwwwwwbkrrk..........",
        "..........krrkgwwwwwwwwwwgkrrk..........",
        "..........krrkBwwwwwwwwwwBkrrk..........",
        "..........krrkBWWWWWWWWWWBkrrk..........",
        "..........kRRkBWWWWWWWWWWBkRRk..........",
        "..........kRRrkBgWWWWWWgBkrRRk..........",
        "..........kkkkkkBBBBBBBBkkkkkk..........",
        "...........krrk.kkkkkkkk.krrk...........",
        "...........krrk..........krrk...........",
        "...........krrk..........krrk...........",
        "..........kBBBk..........kBBBk..........",
        "..........kBBBk..........kBBBk..........",
        "........................................",
        "........................................",
    ])

    private static let walkRise = make("oni.walk.rise", rows: [
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        ".............kwk........kwk.............",
        "............kwWk........kWwk............",
        "............kwWk.kk.....kWwk............",
        "...........khhhhkhhkkkkkhhhhk...........",
        "..........khhhhhhhhhhhhhhhhhhk..........",
        "..........khhhhhhhhhhhhhhhhhhhk.........",
        "..........khhhhhhhhhhhhhhhhhhk..........",
        "..........khhhcchhccchcchhchhk..........",
        "...........krcccckcccckccccrk...........",
        "...........krkkkkkcccckkkkkrk...........",
        "...........krkwwwkcccckwwwkrk...........",
        "...........krkwkwkcccckwkwkrk...........",
        ".......kkk.krccccccRRccccccrk...........",
        ".......ksk.krcckwkkkkkkwkccrk.kkk.......",
        ".......ksk.krcckwkkkkkkwkccrk.ksk.......",
        ".......ksk.krcckkkkkkkkkkccrk.ksk.......",
        ".......ksk.kRrrrrrrrrrrrrrrRk.ksk.......",
        ".......ksk..kkkkkkkkkkkkkkkk..ksk.......",
        ".......ksk.kcccccccccccccccck.ksk.......",
        ".......kskkrccBccccccccccBccrkksk.......",
        ".......krrkrcccBccccccccBcccrkrrk.......",
        ".......krrkrccccckkkkkkcccccrkrrk.......",
        "........kkkrccckkbbbbbbkkcccrkkk........",
        "..........krcckbgwwwwwwgbkccrk..........",
        "..........krrkbwwwwwwwwwwbkrrk..........",
        "..........krrkgwwwwwwwwwwgkrrk..........",
        "..........krrkBwwwwwwwwwwBkrrk..........",
        "..........krrkBWWWWWWWWWWBkrrk..........",
        "..........kRRkBWWWWWWWWWWBkRRk..........",
        "..........kRRrkBgWWWWWWgBkrRRk..........",
        "..........kkkkkkBBBBBBBBkkkkkk..........",
        "............krrkkkkkkkkkkrrk............",
        "............krrk........krrk............",
        "............krrk........krrk............",
        "............krrk........krrk............",
        "...........kBBBk........kBBBk...........",
        "...........kBBBk........kBBBk...........",
        "........................................",
        "........................................",
    ])

    private static let walkCross = make("oni.walk.cross", rows: [
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        ".............kwk........kwk.............",
        "............kwWk........kWwk............",
        "............kwWk.kk.....kWwk............",
        "...........khhhhkhhkkkkkhhhhk...........",
        "..........khhhhhhhhhhhhhhhhhhk..........",
        "..........khhhhhhhhhhhhhhhhhhhk.........",
        "..........khhhhhhhhhhhhhhhhhhk..........",
        "..........khhhcchhccchcchhchhk..........",
        "...........krcccckcccckccccrk...........",
        "...........krkkkkkcccckkkkkrk...........",
        "...........krkwwwkcccckwwwkrk...........",
        ".......kkk.krkwkwkcccckwkwkrk...........",
        ".......ksk.krccccccRRccccccrk...........",
        ".......ksk.krcckwkkkkkkwkccrk...........",
        ".......ksk.krcckwkkkkkkwkccrk.kkk.......",
        ".......ksk.krcckkkkkkkkkkccrk.ksk.......",
        ".......ksk.kRrrrrrrrrrrrrrrRk.ksk.......",
        ".......ksk..kkkkkkkkkkkkkkkk..ksk.......",
        ".......ksk.kcccccccccccccccck.ksk.......",
        ".......krrkrccBccccccccccBccrkksk.......",
        ".......krrkrcccBccccccccBcccrkksk.......",
        "........kkkrccccckkkkkkcccccrkrrk.......",
        "..........krccckkbbbbbbkkcccrkrrk.......",
        "..........krcckbgwwwwwwgbkccrkkk........",
        "..........krrkbwwwwwwwwwwbkrrk..........",
        "..........krrkgwwwwwwwwwwgkrrk..........",
        "..........krrkBwwwwwwwwwwBkrrk..........",
        "..........krrkBWWWWWWWWWWBkrrk..........",
        "..........kRRkBWWWWWWWWWWBkRRk..........",
        "..........kRRrkBgWWWWWWgBkrRRk..........",
        "..........kkkkkkBBBBBBBBkkkkkk..........",
        "...............krrkkkkrrk...............",
        "...............krrk..krrk...............",
        "...............krrk..krrk...............",
        "...............krrk..krrk...............",
        "...............krrk..krrk...............",
        "..............kBBBk..kBBBk..............",
        "..............kBBBk..kBBBk..............",
        "........................................",
        "........................................",
    ])

    private static let walkSettle = make("oni.walk.settle", rows: [
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        ".............kwk........kwk.............",
        "............kwWk........kWwk............",
        "............kwWk.kk.....kWwk............",
        "...........khhhhkhhkkkkkhhhhk...........",
        "..........khhhhhhhhhhhhhhhhhhk..........",
        "..........khhhhhhhhhhhhhhhhhhhk.........",
        "..........khhhhhhhhhhhhhhhhhhk..........",
        "..........khhhcchhccchcchhchhk..........",
        "...........krcccckcccckccccrk...........",
        "...........krkkkkkcccckkkkkrk...........",
        "...........krkwwwkcccckwwwkrk...........",
        "...........krkwkwkcccckwkwkrk...........",
        "...........krccccccRRccccccrk...........",
        ".......kkk.krcckwkkkkkkwkccrk...........",
        ".......ksk.krcckwkkkkkkwkccrk.kkk.......",
        ".......ksk.krcckkkkkkkkkkccrk.ksk.......",
        ".......ksk.kRrrrrrrrrrrrrrrRk.ksk.......",
        ".......ksk..kkkkkkkkkkkkkkkk..ksk.......",
        ".......ksk.kcccccccccccccccck.ksk.......",
        ".......kskkrccBccccccccccBccrkksk.......",
        ".......kskkrcccBccccccccBcccrkksk.......",
        ".......krrkrccccckkkkkkcccccrkrrk.......",
        ".......krrkrccckkbbbbbbkkcccrkrrk.......",
        "........kkkrcckbgwwwwwwgbkccrkkk........",
        "..........krrkbwwwwwwwwwwbkrrk..........",
        "..........krrkgwwwwwwwwwwgkrrk..........",
        "..........krrkBwwwwwwwwwwBkrrk..........",
        "..........krrkBWWWWWWWWWWBkrrk..........",
        "..........kRRkBWWWWWWWWWWBkRRk..........",
        "..........kRRrkBgWWWWWWgBkrRRk..........",
        "..........kkkkkkBBBBBBBBkkkkkk..........",
        ".............krrkkkkkkkkrrk.............",
        ".............krrk......krrk.............",
        ".............krrk......krrk.............",
        ".............krrk......krrk.............",
        "............kBBBk......kBBBk............",
        "............kBBBk......kBBBk............",
        "........................................",
        "........................................",
    ])

    private static let strongAnticipate = make("oni.strong.anticipate", rows: [
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        ".......kkk..............................",
        ".......ksk....................kkk.......",
        ".......ksk....................ksk.......",
        ".......ksk...kwk........kwk...ksk.......",
        ".......ksk..kwWk........kWwk..ksk.......",
        ".......ksk..kwWk.kk.....kWwk..ksk.......",
        ".......ksk.khhhhkhhkkkkkhhhhk.ksk.......",
        ".......kskkhhhhhhhhhhhhhhhhhhkksk.......",
        ".......kskkhhhhhhhhhhhhhhhhhhhksk.......",
        ".......krrkhhhhhhhhhhhhhhhhhhkksk.......",
        ".......krrkhhhcchhccchcchhchhkrrk.......",
        ".......krrkkrcccckcccckccccrkkrrk.......",
        ".......krrkkrkkkkkcccckkkkkrkkrrk.......",
        ".......krrkkrkwwwkcccckwwwkrkkrrk.......",
        ".......krrkkrkwkwkcccckwkwkrkkrrk.......",
        ".......krrkkrccccccRRccccccrkkrrk.......",
        ".......krrkkrcckwkkkkkkwkccrkkrrk.......",
        ".......krrkkrcckwkkkkkkwkccrkkrrk.......",
        ".......krrkkrcckkkkkkkkkkccrkkrrk.......",
        ".......krrkkRrrrrrrrrrrrrrrRkkrrk.......",
        ".......kkkk.kkkkkkkkkkkkkkkk.krrk.......",
        "...........kcccccccccccccccckkkkk.......",
        "..........krccBccccccccccBccrk..........",
        "..........krcccBccccccccBcccrk..........",
        "..........krccccckkkkkkcccccrk..........",
        "..........krccckkbbbbbbkkcccrk..........",
        "..........krcckbgwwwwwwgbkccrk..........",
        "..........krrkbwwwwwwwwwwbkrrk..........",
        "..........krrkgwwwwwwwwwwgkrrk..........",
        "..........krrkBwwwwwwwwwwBkrrk..........",
        "..........krrkBWWWWWWWWWWBkrrk..........",
        "..........kRRkBWWWWWWWWWWBkRRk..........",
        "..........kRRrkBgWWWWWWgBkrRRk..........",
        "..........kkkkkkBBBBBBBBkkkkkk..........",
        "............krrkkkkkkkkkkrrk............",
        "............krrk........krrk............",
        "...........kBBBk........kBBBk...........",
        "...........kBBBk........kBBBk...........",
        "........................................",
        "........................................",
    ])

    private static let strongStrike = make("oni.strong.strike", rows: [
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        ".............kwk........kwk.............",
        "............kwWk........kWwk............",
        "............kwWk.kk.....kWwk............",
        "...........khhhhkhhkkkkkhhhhk...........",
        "..........khhhhhhhhhhhhhhhhhhk..........",
        "..........khhhhhhhhhhhhhhhhhhhk.........",
        "..........khhhhhhhhhhhhhhhhhhk..........",
        "..........khhhcchhccchcchhchhk..........",
        "...........krcccckcccckccccrk...........",
        "...........krkkkkkcccckkkkkrk...........",
        "...........krkwwwkcccckwwwkrk...........",
        "...........krkwkwkcccckwkwkrk...........",
        "...........krccccccRRccccccrk...........",
        "...........krcckwkkkkkkwkccrk...........",
        "...........krcckwkkkkkkwkccrk...........",
        "...........krcckkkkkkkkkkccrk...........",
        "...........kRrrrrrrrrrrrrrrRk...........",
        "............kkkkkkkkkkkkkkkk............",
        "...........kcccccccccccccccck...........",
        "..........krccBccccccccccBccrk..........",
        ".......krkskcccBccccccccBccckskrk.......",
        ".......krrkskcccckkkkkkcccckskrrk.......",
        "........kkkkskckkbbbbbbkkckskkkk........",
        "..........krkskbgwwwwwwgbkskrk..........",
        "..........krrkskgwwwwwwgkskrrk..........",
        "..........krrkkswwwwwwwwskkrrk..........",
        "..........krrkBkwwwwwwwwkBkrrk..........",
        "..........krrkBWWWWWWWWWWBkrrk..........",
        "..........kRRkBWWWWWWWWWWBkRRk..........",
        "..........kRRrkBgWWWWWWgBkrRRk..........",
        "..........kkkkkkBBBBBBBBkkkkkk..........",
        "............krrkkkkkkkkkkrrk............",
        "............krrk........krrk............",
        "............krrk........krrk............",
        "...........kBBBk........kBBBk...........",
        "...........kBBBk........kBBBk...........",
        "........................................",
        "........................................",
    ])

    static let idle: [PixelSpriteDefinition] = [idleNeutral]
    static let walk: [PixelSpriteDefinition] = [walkContact, walkRise, walkCross, walkSettle]
    static let strong: [PixelSpriteDefinition] = [strongAnticipate, strongStrike]

    static let allDefinitions: [PixelSpriteDefinition] = idle + walk + strong
}
