enum TenguSpriteArt {
    static let palette: [Character: UInt32] = [
        "k": 0x24160f,
        "R": 0x8e2f2d,
        "r": 0xc94545,
        "c": 0xe45c5e,
        "h": 0xf37a76,
        "w": 0xfff3da,
        "N": 0x3a4a6e,
        "n": 0x28324e,
        "D": 0x141a30,
        "G": 0x5a8a4e,
        "d": 0x3d6337,
        "B": 0x4a2e1f,
    ]

    private static func make(_ name: String, rows: [String]) -> PixelSpriteDefinition {
        PixelSpriteDefinition(
            name: name,
            rows: rows,
            palette: palette,
            anchorX: 20,
            baselineY: 45
        )
    }

    private static let idleNeutral = make("tengu.idle", rows: [
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        ".................kDDDDk.................",
        ".................kDwnDk.................",
        "................kDDDDDDk................",
        ".............kcccccccccccck.............",
        "............kcccccccccccccck............",
        "...........krwwwwwRhhRwwwwwrk...........",
        "...........krkkkkkRhhRkkkkkrk...........",
        "...........krkwwwkRhhRkwwwkrk.kGk.......",
        "...........krkwkwkRhhRkwkwkrkkGGGk......",
        "...........krcccckhhhRkccccrkkGdGk......",
        "...........krccckhhhhRkccccrkkGdGk......",
        "...........krccckhhhRRkccccrkkGdGk......",
        "........kDkkrckwwkkkkkwwwkcrkkGdGk......",
        ".......kDDkkrcccckwwwwkccccrkkGdGk......",
        ".......kDnDkkRrrrkwwwwkrrrRkkkGdGk......",
        "......kDnDDDkkRrrrkwwkrrrRkkDkGGGk......",
        "......kDnDDDDkkkkkkkkkkkkkkDDDkGkk......",
        "......kDnDDkkNNNNNNNNNNNNNNkkDkdkk......",
        "......kDkNNknNNNNNNNNNNNNNNkNNkBkk......",
        "......kDkNNknNkwwkNNNNkwwkNnkNkBkk......",
        "........knnknNkwwkNNNNkwwkNnknkBk.......",
        "........knnkDDDDDDDDDDDDDDDDkkrck.......",
        "........krckDnnnnnnnnnnnnnnDk.kk........",
        ".........kkkDnnnnnnnnnnnnnnDk...........",
        "..........kDnnnDnnnnnnnnDnnnDk..........",
        "..........kDnnnDnnnnnnnnDnnnDk..........",
        "..........kDnnnDnnnnnnnnDnnnDk..........",
        "..........kDDnnnnnnnnnnnnnnDDk..........",
        "..........kkkkkkkkkkkkkkkkkkkk..........",
        ".............kwwk......kwwk.............",
        ".............kwwk......kwwk.............",
        ".............kwwk......kwwk.............",
        ".............kwwk......kwwk.............",
        ".............kwwk......kwwk.............",
        ".............kwwk......kwwk.............",
        "............kBBBBk....kBBBBk............",
        "..............kBk.......kBk.............",
        "..............kBk.......kBk.............",
        "..............kBk.......kBk.............",
        "........................................",
        "........................................",
    ])

    private static let walkContact = make("tengu.walk.contact", rows: [
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        ".................kDDDDk.................",
        ".................kDwnDk.................",
        "................kDDDDDDk................",
        ".............kcccccccccccck.............",
        "............kcccccccccccccck............",
        "...........krwwwwwRhhRwwwwwrk...........",
        "...........krkkkkkRhhRkkkkkrk...........",
        "...........krkwwwkRhhRkwwwkrk...........",
        "...........krkwkwkRhhRkwkwkrk.kGk.......",
        "...........krcccckhhhRkccccrkkGGGk......",
        "...........krccckhhhhRkccccrkkGdGk......",
        "...........krccckhhhRRkccccrkkGdGk......",
        "........kDkkrckwwkkkkkwwwkcrkkGdGk......",
        ".......kDDkkrcccckwwwwkccccrkkGdGk......",
        ".......kDnDkkRrrrkwwwwkrrrRkkkGdGk......",
        "......kDnDDDkkRrrrkwwkrrrRkkDkGdGk......",
        "......kDnDDDDkkkkkkkkkkkkkkDDkGGGk......",
        "......kDkNNkkNNNNNNNNNNNNNNkkDkGkk......",
        "......kDkNNknNNNNNNNNNNNNNNnkkkdkk......",
        "......kDknnknNkwwkNNNNkwwkNkNNkBkk......",
        "........knnknNkwwkNNNNkwwkNnkNkBk.......",
        "........krckDDDDDDDDDDDDDDDDknkBk.......",
        ".........kkkDnnnnnnnnnnnnnnDkkrck.......",
        "...........kDnnnnnnnnnnnnnnDkkkk........",
        "..........kDnnnDnnnnnnnnDnnnDk..........",
        "..........kDnnnDnnnnnnnnDnnnDk..........",
        "..........kDnnnDnnnnnnnnDnnnDk..........",
        "..........kDDnnnnnnnnnnnnnnDDk..........",
        "..........kkkkkkkkkkkkkkkkkkkk..........",
        "............kwwk........kwwk............",
        "............kwwk........kwwk............",
        "............kwwk........kwwk............",
        "............kwwk........kwwk............",
        "............kwwk........kwwk............",
        "............kwwk........kwwk............",
        "...........kBBBBk......kBBBBk...........",
        ".............kBk.........kBk............",
        ".............kBk.........kBk............",
        ".............kBk.........kBk............",
        "........................................",
        "........................................",
    ])

    private static let walkRise = make("tengu.walk.rise", rows: [
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        ".................kDDDDk.................",
        ".................kDwnDk.................",
        "................kDDDDDDk................",
        ".............kcccccccccccck.............",
        "............kcccccccccccccck............",
        "...........krwwwwwRhhRwwwwwrk...........",
        "...........krkkkkkRhhRkkkkkrk...........",
        "...........krkwwwkRhhRkwwwkrk.kGk.......",
        "...........krkwkwkRhhRkwkwkrkkGGGk......",
        "...........krcccckhhhRkccccrkkGdGk......",
        "...........krccckhhhhRkccccrkkGdGk......",
        "...........krccckhhhRRkccccrkkGdGk......",
        "........kDkkrckwwkkkkkwwwkcrkkGdGk......",
        ".......kDDkkrcccckwwwwkccccrkkGdGk......",
        ".......kDnDkkRrrrkwwwwkrrrRkkkGdGk......",
        "......kDnDDDkkRrrrkwwkrrrRkkDkGGGk......",
        "......kDnDDDDkkkkkkkkkkkkkkDDDkGkk......",
        "......kDnDDkkNNNNNNNNNNNNNNkkDkdkk......",
        "......kDkNNknNNNNNNNNNNNNNNkNNkBkk......",
        "......kDkNNknNkwwkNNNNkwwkNnkNkBkk......",
        "........knnknNkwwkNNNNkwwkNnknkBk.......",
        "........knnkDDDDDDDDDDDDDDDDkkrck.......",
        "........krckDnnnnnnnnnnnnnnDk.kk........",
        ".........kkkDnnnnnnnnnnnnnnDk...........",
        "..........kDnnnDnnnnnnnnDnnnDk..........",
        "..........kDnnnDnnnnnnnnDnnnDk..........",
        "..........kDnnnDnnnnnnnnDnnnDk..........",
        "..........kDDnnnnnnnnnnnnnnDDk..........",
        "..........kkkkkkkkkkkkkkkkkkkk..........",
        ".............kwwk......kwwk.............",
        ".............kwwk......kwwk.............",
        ".............kwwk......kwwk.............",
        ".............kwwk......kwwk.............",
        ".............kwwk......kwwk.............",
        ".............kwwk......kwwk.............",
        ".............kwwk......kwwk.............",
        "............kBBBBk....kBBBBk............",
        "..............kBk.......kBk.............",
        "..............kBk.......kBk.............",
        "..............kBk.......kBk.............",
        "........................................",
        "........................................",
    ])

    private static let walkCross = make("tengu.walk.cross", rows: [
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        ".................kDDDDk.................",
        ".................kDwnDk.................",
        "................kDDDDDDk................",
        ".............kcccccccccccck.............",
        "............kcccccccccccccck............",
        "...........krwwwwwRhhRwwwwwrk...........",
        "...........krkkkkkRhhRkkkkkrk.kGk.......",
        "...........krkwwwkRhhRkwwwkrkkGGGk......",
        "...........krkwkwkRhhRkwkwkrkkGdGk......",
        "...........krcccckhhhRkccccrkkGdGk......",
        "...........krccckhhhhRkccccrkkGdGk......",
        "...........krccckhhhRRkccccrkkGdGk......",
        "........kDkkrckwwkkkkkwwwkcrkkGdGk......",
        ".......kDDkkrcccckwwwwkccccrkkGdGk......",
        ".......kDnDkkRrrrkwwwwkrrrRkkkGGGk......",
        "......kDnDDDkkRrrrkwwkrrrRkkDDkGkk......",
        "......kDnDDDDkkkkkkkkkkkkkkDDDkdkk......",
        "......kDnDDkkNNNNNNNNNNNNNNkNNkBkk......",
        "......kDnDkknNNNNNNNNNNNNNNnkNkBkk......",
        "......kDkNNknNkwwkNNNNkwwkNnknkBkk......",
        "........kNNknNkwwkNNNNkwwkNnkkrck.......",
        "........knnkDDDDDDDDDDDDDDDDk.kk........",
        "........knnkDnnnnnnnnnnnnnnDk...........",
        "........krckDnnnnnnnnnnnnnnDk...........",
        ".........kkDnnnDnnnnnnnnDnnnDk..........",
        "..........kDnnnDnnnnnnnnDnnnDk..........",
        "..........kDnnnDnnnnnnnnDnnnDk..........",
        "..........kDDnnnnnnnnnnnnnnDDk..........",
        "..........kkkkkkkkkkkkkkkkkkkk..........",
        "...............kwwk..kwwk...............",
        "...............kwwk..kwwk...............",
        "...............kwwk..kwwk...............",
        "...............kwwk..kwwk...............",
        "...............kwwk..kwwk...............",
        "...............kwwk..kwwk...............",
        "...............kwwk..kwwk...............",
        "..............kBBBBkkBBBBk..............",
        "................kBk...kBk...............",
        "................kBk...kBk...............",
        "................kBk...kBk...............",
        "........................................",
        "........................................",
    ])

    private static let walkSettle = make("tengu.walk.settle", rows: [
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        ".................kDDDDk.................",
        ".................kDwnDk.................",
        "................kDDDDDDk................",
        ".............kcccccccccccck.............",
        "............kcccccccccccccck............",
        "...........krwwwwwRhhRwwwwwrk...........",
        "...........krkkkkkRhhRkkkkkrk...........",
        "...........krkwwwkRhhRkwwwkrk.kGk.......",
        "...........krkwkwkRhhRkwkwkrkkGGGk......",
        "...........krcccckhhhRkccccrkkGdGk......",
        "...........krccckhhhhRkccccrkkGdGk......",
        "...........krccckhhhRRkccccrkkGdGk......",
        "........kDkkrckwwkkkkkwwwkcrkkGdGk......",
        ".......kDDkkrcccckwwwwkccccrkkGdGk......",
        ".......kDnDkkRrrrkwwwwkrrrRkkkGdGk......",
        "......kDnDDDkkRrrrkwwkrrrRkkDkGGGk......",
        "......kDnDDDDkkkkkkkkkkkkkkDDDkGkk......",
        "......kDnDDkkNNNNNNNNNNNNNNkkDkdkk......",
        "......kDkNNknNNNNNNNNNNNNNNkNNkBkk......",
        "......kDkNNknNkwwkNNNNkwwkNnkNkBkk......",
        "........knnknNkwwkNNNNkwwkNnknkBk.......",
        "........knnkDDDDDDDDDDDDDDDDkkrck.......",
        "........krckDnnnnnnnnnnnnnnDk.kk........",
        ".........kkkDnnnnnnnnnnnnnnDk...........",
        "..........kDnnnDnnnnnnnnDnnnDk..........",
        "..........kDnnnDnnnnnnnnDnnnDk..........",
        "..........kDnnnDnnnnnnnnDnnnDk..........",
        "..........kDDnnnnnnnnnnnnnnDDk..........",
        "..........kkkkkkkkkkkkkkkkkkkk..........",
        "..............kwwk....kwwk..............",
        "..............kwwk....kwwk..............",
        "..............kwwk....kwwk..............",
        "..............kwwk....kwwk..............",
        "..............kwwk....kwwk..............",
        "..............kwwk....kwwk..............",
        ".............kBBBBk..kBBBBk.............",
        "...............kBk.....kBk..............",
        "...............kBk.....kBk..............",
        "...............kBk.....kBk..............",
        "........................................",
        "........................................",
    ])

    private static let strongAnticipate = make("tengu.strong.anticipate", rows: [
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "..............................kGk.......",
        ".............................kGGGk......",
        ".............................kGdGk......",
        ".................kDDDDk......kGdGk......",
        ".................kDwnDk......kGdGk......",
        "................kDDDDDDk.....kGdGk......",
        ".............kcccccccccccck..kGdGk......",
        "............kcccccccccccccck.kGGGk......",
        "...........krwwwwwRhhRwwwwwrk.kGk.......",
        "...........krkkkkkRhhRkkkkkrk.kdk.......",
        "...........krkwwwkRhhRkwwwkrk.kBk.......",
        "...........krkwkwkRhhRkwkwkrk.kBk.......",
        "...........krcccckhhhRkccccrkkrck.......",
        "...........krccckhhhhRkccccrkkrck.......",
        "...........krccckhhhRRkccccrkNNk........",
        "...........krckwwkkkkkwwwkcrkNNk........",
        "...........krcccckwwwwkccccrkNNk........",
        ".........kDkkRrrrkwwwwkrrrRkkNNk........",
        "........kDnDkkRrrrkwwkrrrRkkkNNk........",
        "........kDnDDkkkkkkkkkkkkkkDkNNk........",
        "........kDnDkNNNNNNNNNNNNNNkkNNk........",
        "........kNNknNNNNNNNNNNNNNNnkkDk........",
        "........kNNknNkwwkNNNNkwwkNnk...........",
        "........knnknNkwwkNNNNkwwkNnk...........",
        "........knnkDDDDDDDDDDDDDDDDk...........",
        "........krckDnnnnnnnnnnnnnnDk...........",
        ".........kkkDnnnnnnnnnnnnnnDk...........",
        "..........kDnnnDnnnnnnnnDnnnDk..........",
        "..........kDnnnDnnnnnnnnDnnnDk..........",
        "..........kDnnnDnnnnnnnnDnnnDk..........",
        "..........kDDnnnnnnnnnnnnnnDDk..........",
        "..........kkkkkkkkkkkkkkkkkkkk..........",
        ".............kwwk......kwwk.............",
        ".............kwwk......kwwk.............",
        ".............kwwk......kwwk.............",
        ".............kwwk......kwwk.............",
        ".............kwwk......kwwk.............",
        ".............kwwk......kwwk.............",
        "............kBBBBk....kBBBBk............",
        "..............kBk.......kBk.............",
        "..............kBk.......kBk.............",
        "..............kBk.......kBk.............",
        "........................................",
        "........................................",
    ])

    private static let strongHit = make("tengu.strong.hit", rows: [
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        ".................kDDDDk.................",
        ".................kDwnDk.................",
        "................kDDDDDDk................",
        ".............kcccccccccccck.............",
        "............kcccccccccccccck............",
        "...........krwwwwwRhhRwwwwwrk...........",
        "...........krkkkkkRhhRkkkkkrk...........",
        "...........krkwwwkRhhRkwwwkrk...........",
        "...........krkwkwkRhhRkwkwkrk...........",
        "...........krcccckhhhRkccccrk...........",
        "...........krccckhhhhRkccccrk...........",
        "...........krccckhhhRRkccccrk.kDk.......",
        "........kDkkrckwwkkkkkwwwkcrkkDDDk......",
        ".......kDDkkrcccckwwwwkccccrkkDnDDk.....",
        ".......kDnDkkRrrrkwwwwkrrrRkkDnnDDk.....",
        "......kDnDDDkkRrrrkwwkrrrRkkDDnnDDk.....",
        "......kDnDDDDkkkkkkkkkkkkkkkDDnnDDDk....",
        "......kDnDDkkNNNNNNNNNNNNNNkkDnnDDDk....",
        "......kDkNNknNNNNNNNNNNNNNNnkkDnDDk.....",
        "......kDkNNknNkwwkNNNNkwwkNNk....kDk....",
        "........knnknNkwwkNNNNkNNNknk...........",
        "......kkkkkkDDDDDDDkNNNkDDDDk...........",
        ".....kGGGGGGGkrcknnnknnnnnnDk...........",
        "....kGGddddddkrcknnnnnnnnnnDk...........",
        ".....kddddddknnDnnnnnnnnDnnnDk..........",
        "......kkkkkknnnDnnnnnnnnDnnnDk..........",
        "..........kDnnnDnnnnnnnnDnnnDk..........",
        "..........kDDnnnnnnnnnnnnnnDDk..........",
        "..........kkkkkkkkkkkkkkkkkkkk..........",
        ".............kwwk......kwwk.............",
        ".............kwwk......kwwk.............",
        ".............kwwk......kwwk.............",
        ".............kwwk......kwwk.............",
        ".............kwwk......kwwk.............",
        ".............kwwk......kwwk.............",
        "............kBBBBk....kBBBBk............",
        "..............kBk.......kBk.............",
        "..............kBk.......kBk.............",
        "..............kBk.......kBk.............",
        "........................................",
        "........................................",
    ])

    static let idle: [PixelSpriteDefinition] = [idleNeutral]
    static let walk: [PixelSpriteDefinition] = [walkContact, walkRise, walkCross, walkSettle]
    static let strong: [PixelSpriteDefinition] = [strongAnticipate, strongHit]

    static let allDefinitions: [PixelSpriteDefinition] = idle + walk + strong
}
